### ISSUE TITLE
Crediting you in a paper about lens shading

### ISSUE THREAD

**Issue by rwb27** [6by9/lens_shading#1]
I've done some work that builds on your work on the lens shading tables for the Raspberry Pi camera - specifically a Python wrapper, and some thinking about how to calibrated the system with different optics.  Obviously I've linked back to the various libraries and repositories, but this will be an academic paper, and at the moment those links appear in citations which don't have an author associated with them.
  I am very keen to give credit where it's due - but I don't know how you'd prefer me to credit you.  If you would like your name mentioned, I'll make sure it is included - if you'd prefer I use 6by9 that is of course fine.  I just didn't want to assume either way.

Thanks again for all the very many things you do for the Raspberry Pi community!

PS the manuscript and most of the associated maths are here:
https://gitlab.com/bath_open_instrumentation_group/picamera_cra_compensation
I suspect none of it will be new to you - but I thought it would be worth writing it up because I had to work through it anyway.  An open-access publication and suitably tidied up source code will appear in the near future I hope.

**Comment by 6by9** [comment]
Sorry for not replying sooner. 

No personal credit required as I'm an emloyee of Raspberry Pi and paid to do this, but you can credit me as Dave Stevenson if you wish.

**Comment by rwb27** [comment]
Hello,
  I'm paid to do this too, but I'm still keen to give credit where it's due!  I have added you to the acknowledgements section as is standard practice for this sort of paper.  Thanks again for making lens shading and gain control possible, it's really changed what we can do with the camera!
